### ISSUE TITLE
vm 虚拟机执行 ./script/create-dist.sh 找不到java类

### ISSUE THREAD

**Issue by stathamcheng** [virjarRatel/ratel-core#2]
BUILD SUCCESSFUL in 1m 52s
135 actionable tasks: 120 executed, 15 up-to-date
replace BuildEnv.class
# input and output
-libraryjars /usr/lib/jvm/java-9-openjdk-amd64/jmods/java.base.jmod(!**.jar;!module-info.class)
-injars /tmp/rdp-tmp16539001164654877404.jar
-outjars /tmp/builder-opt2662734108458548883.jar
-printmapping  /tmp/builder-proguard.map
# builder 的优化规则
-keepattributes *

# 貌似大小写会出问题，导致文件名大写，对应class小写
-dontusemixedcaseclassnames

# ratel 框架入口class
-keep  class com.virjar.ratel.rdp.RDPBuilder {
    public static void main(java.lang.String[]);
}

-keep class org.jf.dexlib2.Opcode{*;}

-keep class com.android.apksig.internal.**{*;}

-dontwarn
-dontnote
-ignorewarnings

# 开源环境，我们不做混淆
-dontobfuscate

execute cmd: java -jar /tmp/proguard10857178538044957529.jar @/tmp/proguard11340759816485037197.pro
ProGuard, version undefined
replace BuildEnv.class
# input and output
-libraryjars /usr/lib/jvm/java-9-openjdk-amd64/jmods/java.base.jmod(!**.jar;!module-info.class)
-injars /tmp/builder-dex11647356933490416329.jar
-outjars /tmp/builder-opt16152504066025136237.jar
-printmapping  /tmp/builder-proguard.map
# builder 的优化规则
-keepattributes *

# 貌似大小写会出问题，导致文件名大写，对应class小写
-dontusemixedcaseclassnames

# ratel 框架入口class
-keep  class com.virjar.ratel.builder.ratelentry.Main {
    public static void main(java.lang.String[]);
}

-keep class org.jf.dexlib2.Opcode{*;}

-keep class com.android.apksig.internal.**{*;}

-dontwarn
-dontnote
-ignorewarnings

# 开源环境，我们不做混淆
-dontobfuscate

execute cmd: java -jar /tmp/proguard3626104743551435615.jar @/tmp/proguard18420058970009211339.pro
ProGuard, version undefined
Warning in /tmp/builder-dex11647356933490416329.jar:com/android/apksig/internal/util/X509CertificateUtils.class:
  Type `java.util.Base64` was not found, it is required for default or static interface methods desugaring of `java.nio.ByteBuffer com.android.apksig.internal.util.X509CertificateUtils.getNextDEREncodedCertificateBlock(java.nio.ByteBuffer)`
Warning in /tmp/builder-dex11647356933490416329.jar:com/virjar/ratel/builder/ratelentry/HelperZipAndSign.class:
  Type `java.nio.file.Files` was not found, it is required for default or static interface methods desugaring of `void com.virjar.ratel.builder.ratelentry.HelperZipAndSign.zipalign(java.io.File, java.io.File)`
Warning in /tmp/builder-dex11647356933490416329.jar:com/android/apksig/internal/apk/ApkSigningBlockUtils.class:
  Type `java.util.stream.Collectors` was not found, it is required for default or static interface methods desugaring of `java.util.Map com.android.apksig.internal.apk.ApkSigningBlockUtils.computeContentDigests(com.android.apksig.util.RunnablesExecutor, java.util.Set, com.android.apksig.util.DataSource, com.android.apksig.util.DataSource, com.android.apksig.util.DataSource)`
Warning in /tmp/builder-dex11647356933490416329.jar:com/android/apksig/internal/apk/ApkSigningBlockUtils$ChunkSupplier.class:
  Type `java.util.function.Supplier` was not found, it is required for default or static interface methods desugaring of `com.android.apksig.internal.apk.ApkSigningBlockUtils$ChunkSupplier`
Warning in synthesized for lambda desugaring:
  Type `java.util.function.ToLongFunction` was not found, it is required for default or static interface methods desugaring of `com.android.apksig.internal.util.-$$Lambda$ChainedDataSource$YbhxliLhPY8NWeCBObJtP04F1LE`
Warning in synthesized for lambda desugaring:
  Type `java.util.function.Predicate` was not found, it is required for default or static interface methods desugaring of `com.android.apksig.internal.apk.-$$Lambda$ApkSigningBlockUtils$AeXO_V-y3jcGXA8TwhH3-ZW5RHI`
Warning in synthesized for lambda desugaring:
  Type `java.util.function.Function` was not found, it is required for default or static interface methods desugaring of `org.apache.tools.zip.-$$Lambda$ZipFile$gLw0qrVX7ZhWOQIzPn3nFi3apeo`
replace BuildEnv.class
# input and output
-libraryjars /usr/lib/jvm/java-9-openjdk-amd64/jmods/java.base.jmod(!**.jar;!module-info.class)
-injars /home/virjar/Desktop/ratel/ratel-core/script/dist/res/container-builder-repkg-2.0.0-SNAPSHOT.jar
-outjars /tmp/builder-opt18015309779143679370.jar
-printmapping  /home/virjar/Desktop/ratel/ratel-core/script/dist/res/builder-proguard.map
# builder 的优化规则
-keepattributes *

# 貌似大小写会出问题，导致文件名大写，对应class小写
-dontusemixedcaseclassnames

# ratel 框架入口class
-keep  class com.virjar.ratel.builder.ratelentry.Main {
    public static void main(java.lang.String[]);
}

-keep class org.jf.dexlib2.Opcode{*;}

-keep class com.android.apksig.internal.**{*;}

-dontwarn
-dontnote
-ignorewarnings

# 开源环境，我们不做混淆
-dontobfuscate

execute cmd: java -jar /tmp/proguard17818899127886307114.jar @/tmp/proguard3184489959863318244.pro
ProGuard, version undefined
  adding: ratel.bat (deflated 67%)
  adding: ratel.sh (deflated 64%)
  adding: res/ (stored 0%)
  adding: res/ratel_version.txt (stored 0%)
  adding: res/monthly_temp.txt (deflated 20%)
  adding: res/container-builder-repkg-2.0.0-SNAPSHOT.jar (deflated 3%)
  adding: res/container-builder-repkg-2.0.0-SNAPSHOT-dex.jar (deflated 0%)
  adding: res/hermes_key (deflated 5%)
  adding: res/build_timestamp.txt (stored 0%)
  adding: res/hermes_bksv1_key (deflated 5%)
virjar@virjar-aosp:~/Desktop/ratel/ratel-core$

**Comment by virjar** [comment]
完全看不懂描述的啥东西

**Comment by stathamcheng** [comment]
就是显示BUILD SUCCESSFUL in 1m 52s，过后说找不到java类：

-dontobfuscate

execute cmd: java -jar /tmp/proguard3626104743551435615.jar @/tmp/proguard18420058970009211339.pro
ProGuard, version undefined
Warning in /tmp/builder-dex11647356933490416329.jar:com/android/apksig/internal/util/X509CertificateUtils.class:
Type java.util.Base64 was not found, it is required for default or static interface methods desugaring of java.nio.ByteBuffer com.android.apksig.internal.util.X509CertificateUtils.getNextDEREncodedCertificateBlock(java.nio.ByteBuffer)
Warning in /tmp/builder-dex11647356933490416329.jar:com/virjar/ratel/builder/ratelentry/HelperZipAndSign.class:
Type java.nio.file.Files was not found, it is required for default or static interface methods desugaring of void com.virjar.ratel.builder.ratelentry.HelperZipAndSign.zipalign(java.io.File, java.io.File)
Warning in /tmp/builder-dex11647356933490416329.jar:com/android/apksig/internal/apk/ApkSigningBlockUtils.class:
Type java.util.stream.Collectors was not found, it is required for default or static interface methods desugaring of java.util.Map com.android.apksig.internal.apk.ApkSigningBlockUtils.computeContentDigests(com.android.apksig.util.RunnablesExecutor, java.util.Set, com.android.apksig.util.DataSource, com.android.apksig.util.DataSource, com.android.apksig.util.DataSource)
Warning in /tmp/builder-dex11647356933490416329.jar:com/android/apksig/internal/apk/ApkSigningBlockUtils$ChunkSupplier.class:
Type java.util.function.Supplier was not found, it is required for default or static interface methods desugaring of com.android.apksig.internal.apk.ApkSigningBlockUtils$ChunkSupplier
Warning in synthesized for lambda desugaring:
Type java.util.function.ToLongFunction was not found, it is required for default or static interface methods desugaring of com.android.apksig.internal.util.-$$Lambda$ChainedDataSource$YbhxliLhPY8NWeCBObJtP04F1LE
Warning in synthesized for lambda desugaring:
Type java.util.function.Predicate was not found, it is required for default or static interface methods desugaring of com.android.apksig.internal.apk.-$$Lambda$ApkSigningBlockUtils$AeXO_V-y3jcGXA8TwhH3-ZW5RHI
Warning in synthesized for lambda desugaring:
Type java.util.function.Function was not found, it is required for default or static interface methods desugaring of org.apache.tools.zip.-$$Lambda$ZipFile$gLw0qrVX7ZhWOQIzPn3nFi3apeo
replace BuildEnv.class

**Comment by virjar** [comment]
额。。。这是警告，涉及到java和android平台的一些细小差异。
比如```java.util.function.Function```是jdk8才会有的东西，有些库里面使用了jdk8的这些东西，但是我们实际上希望我们的工具可以在jdk7上面运行（没记错的话，对标到Android大概是Android7对应jdk7）。

故这是一个java语法脱糖的过程，这个过程所有java8语法降级到java7上面都可以。这个知识你要是开发过Android自然就应该懂得。 [https://www.freesion.com/article/33001424487/](https://www.freesion.com/article/33001424487/)

总结起来，这个告警是几乎所有的Android代码在编译过程都会发生的（希望app运行在Android7以及一下的设备上，但是代码以来的api在java8上面构建）。忽略即可。至于为啥会报警，为啥这个报警对我们的程序没有影响，篇幅有限，不太方便展开，你自己研究吧。

issues我关闭了，下次提问题好好做一下排版，清楚的描述你的问题。否则不回答直接close

**Comment by stathamcheng** [comment]
好的！感谢大哥的解答！下次会注意。
