### ISSUE TITLE
您好我看您发布的2.0版本是14mb的我自己打包出来的只有4mb并且闪退是什么原因呢

### ISSUE THREAD

**Issue by xiaotujinbnb** [virjarRatel/ratel-core#4]
这里放我打包的a
[Uploading RatelManager_2.0-SNAPSHOT-debug.apk.zip…]()
pk

**Comment by virjar** [comment]
![image](https://user-images.githubusercontent.com/15690933/142710289-8e2b648d-07fb-45f0-aa48-0b54ae53d6ac.png)

另外闪退请给日志，你不给日志我怎么知道为啥闪退。。。。

**Comment by virjar** [comment]
close无效issue
